export const USER_LOGOUT = 'USER_LOGOUT'
export const SET_TOKEN_ACTION = 'SET_TOKEN_ACTION'
export const CREATE_ACCOUNT_ACTION = 'CREATE_ACCOUNT_ACTION'
export const CREATE_ACCOUNT_LOADING = 'CREATE_ACCOUNT_LOADING'
export const SET_USER_ACTION = 'SET_USER_ACTION'
export const UPDATE_USER_ACTION = 'UPDATE_USER_ACTION'
export const SET_NETWORK_CONFIG = 'SET_NETWORK_CONFIG'
export const UPDATE_ACCOUNT_ACTION = "UPDATE_ACCOUNT_ACTION"
export const LOGOUT_ACTION = "LOGOUT_ACTION"

export const LOAD_USER_TRANSACTION_ACTION = "LOAD_USER_TRANSACTION_ACTION"
export const LOAD_USER_TRANSACTION_LOADING = "LOAD_USER_TRANSACTION_LOADING"
export const SET_USER_TRANSACTION = "SET_USER_TRANSACTION"
export const UPDATE_USER_ONBOARDING_COUNT_ACTION = "UPDATE_USER_ONBOARDING_COUNT_ACTION"
export const LOAD_DAOLIST_ACTION = "LOAD_DAOLIST_ACTION"
export const LOAD_DAOLIST_LOADING = "LOAD_DAOLIST_LOADING"
export const LOAD_DAOLIST_SUCCESS = "LOAD_DAOLIST_SUCCESS"

export const RESET_DAO_ACTION = "RESET_DAO_ACTION"
export const LOAD_DAO_ACTION = "LOAD_DAO_ACTION"
export const LOAD_DAO_LOADING = "LOAD_DAO_LOADING"
export const LOAD_DAO_SUCCESS = "LOAD_DAO_SUCCESS"
export const SET_DAO_ACTION = "SET_DAO_ACTION"
export const SET_DAO_MEMBER_ACTION = "SET_DAO_MEMBER_ACTION"
export const TOGGLE_SAFE_ACTION = "TOGGLE_SAFE_ACTION"

export const ADD_DAO_MEMBER_ACTION = "ADD_DAO_MEMBER_ACTION"

export const ADD_SINGLE_MEMBER_ACTION = "ADD_SINGLE_MEMBER_ACTION"
export const ADD_SINGLE_MEMBER_LOADING = "ADD_SINGLE_MEMBER_LOADING"

export const ADD_MULTI_MEMBER_ACTION = "ADD_MULTI_MEMBER_ACTION"
export const ADD_MULTI_MEMBER_LOADING = "ADD_MULTI_MEMBER_LOADING"

export const EDIT_DAO_MEMBER_ACTION = "EDIT_DAO_MEMBER_ACTION"
export const EDIT_DAO_MEMBER_LOADING = "EDIT_DAO_MEMBER_LOADING"

export const UPDATE_DAO_MEMBERS_ACTION = "UPDATE_DAO_MEMBERS_ACTION"
export const UPDATE_DAO_MEMBERS_LOADING = "UPDATE_DAO_MEMBERS_LOADING"

// PROJECT

export const GET_PROJECT_ACTION = 'GET_PROJECT_ACTION'

export const SET_PROJECT_ACTION = 'SET_PROJECT_ACTION'
export const SET_PROJECT_LOADING = 'SET_PROJECT_LOADING'

export const CREATE_PROJECT_ACTION = 'CREATE_PROJECT_ACTION'
export const CREATE_PROJECT_LOADING = 'CREATE_PROJECT_LOADING'

export const UPDATE_PROJECT_DETAILS_ACTION = 'UPDATE_PROJECT_DETAILS_ACTION'
export const UPDATE_PROJECT_DETAILS_LOADING = 'UPDATE_PROJECT_DETAILS_LOADING'

export const ARCHIVE_PROJECT_ACTION = 'ARCHIVE_PROJECT_ACTION'
export const ARCHIVE_PROJECT_LOADING = 'ARCHIVE_PROJECT_LOADING'

export const DELETE_PROJECT_ACTION = 'DELETE_PROJECT_ACTION'
export const DELETE_PROJECT_LOADING = 'DELETE_PROJECT_LOADING'

export const UPDATE_PROJECT_KRA_ACTION = 'UPDATE_PROJECT_KRA_ACTION'
export const UPDATE_PROJECT_KRA_LOADING = 'UPDATE_PROJECT_KRA_LOADING'

export const EDIT_PROJECT_KRA_ACTION = 'EDIT_PROJECT_KRA_ACTION'
export const EDIT_PROJECT_KRA_LOADING = 'EDIT_PROJECT_KRA_LOADING'

export const UPDATE_PROJECT_MEMBERS_ACTION = 'UPDATE_PROJECT_MEMBERS_ACTION'
export const UPDATE_PROJECT_MEMBERS_LOADING = 'UPDATE_PROJECT_MEMBERS_LOADING'

export const EDIT_PROJECT_MILESTONES_ACTION = 'EDIT_PROJECT_MILESTONES_ACTION'
export const EDIT_PROJECT_MILESTONES_LOADING = 'EDIT_PROJECT_MILESTONES_LOADING'

export const INVITE_PROJECT_MEMBERS_ACTION = 'INVITE_PROJECT_MEMBERS_ACTION'
export const INVITE_PROJECT_MEMBERS_LOADING = 'INVITE_PROJECT_MEMBERS_LOADING'

export const UPDATE_PROJECT_LINK_ACTION = 'UPDATE_PROJECT_LINK_ACTION'
export const EDIT_PROJECT_LINK_ACTION = 'EDIT_PROJECT_LINK_ACTION'

export const UPDATE_PROJECT_VIEW_ACTION = 'UPDATE_PROJECT_VIEW_ACTION'
export const UPDATE_PROJECT_VIEW_LOADING = 'UPDATE_PROJECT_VIEW_LOADING'

// TASK

export const GET_TASK_ACTION = 'GET_TASK_ACTION'

export const SET_TASK_ACTION = 'SET_TASK_ACTION'
export const SET_TASK_LOADING = 'SET_TASK_LOADING'

export const CREATE_TASK_ACTION = 'CREATE_TASK_ACTION'
export const CREATE_TASK_LOADING = 'CREATE_TASK_LOADING'

export const DRAFT_TASK_ACTION = 'DRAFT_TASK_ACTION'
export const DRAFT_TASK_LOADING = 'DRAFT_TASK_LOADING'

export const EDIT_TASK_ACTION = 'EDIT_TASK_ACTION'
export const EDIT_TASK_LOADING = 'EDIT_TASK_LOADING'

export const EDIT_DRAFT_TASK_ACTION = 'EDIT_DRAFT_TASK_ACTION'
export const EDIT_DRAFT_TASK_LOADING = 'EDIT_DRAFT_TASK_LOADING'

export const CONVERT_DRAFT_TASK_ACTION = 'CONVERT_DRAFT_TASK_ACTION'
export const CONVERT_DRAFT_TASK_LOADING = 'CONVERT_DRAFT_TASK_LOADING'

export const ARCHIVE_TASK_ACTION = 'ARCHIVE_TASK_ACTION'
export const ARCHIVE_TASK_LOADING = 'ARCHIVE_TASK_LOADING'

export const DELETE_TASK_ACTION = 'DELETE_TASK_ACTION'
export const DELETE_TASK_LOADING = 'DELETE_TASK_LOADING'

export const APPLY_TASK_ACTION = 'APPLY_TASK_ACTION'
export const APPLY_TASK_LOADING = 'APPLY_TASK_LOADING'

export const SUBMIT_TASK_ACTION = 'SUBMIT_TASK_ACTION'
export const SUBMIT_TASK_LOADING = 'SUBMIT_TASK_LOADING'

export const ASSIGN_TASK_ACTION = 'ASSIGN_TASK_ACTION'
export const ASSIGN_TASK_LOADING = 'ASSIGN_TASK_LOADING'

export const REJECT_TASK_MEMBER_ACTION = 'REJECT_TASK_MEMBER_ACTION'
export const REJECT_TASK_MEMBER_LOADING = 'REJECT_TASK_MEMBER_LOADING'

export const REJECT_TASK_SUBMISSION_ACTION = 'REJECT_TASK_SUBMISSION_ACTION'
export const REJECT_TASK_SUBMISSION_LOADING = 'REJECT_TASK_SUBMISSION_LOADING'

export const SET_DAO_OPTION_ACTION = "SET_DAO_OPTION_ACTION"
export const UPDATE_DAO_ACTION = "UPDATE_DAO_ACTION"
export const UPDATE_DAO_LOADING = "UPDATE_DAO_LOADING"

export const LOAD_TREASURY_ACTION = "LOAD_TREASURY_ACTION"
export const LOAD_TREASURY_LOADING = "LOAD_TREASURY_LOADING"
export const SET_TREASURY = "SET_TREASURY"
export const CREATE_TREASURY_TRANSACTION_ACTION = "CREATE_TREASURY_TRANSACTION_ACTION"
export const APPEND_TREASURY_TRANSACTION = "APPEND_TREASURY_TRANSACTION"
export const UPDATE_TREASURY_TRANSACTION_ACTION = "UPDATE_TREASURY_TRANSACTION_ACTION"
export const UPDATE_TREASURY_TRANSACTION = "UPDATE_TREASURY_TRANSACTION"
export const UPDATE_TX_LABEL_ACTION = "UPDATE_TX_LABEL_ACTION"
export const SET_TX_LABEL = "SET_TX_LABEL"
export const SYNC_SAFE_ACTION = "SYNC_SAFE_ACTION"
export const UPDATE_MILESTONE_ACTION = "UPDATE_MILESTONE_ACTION"

export const SYNC_TRELLO_DATA_ACTION = 'SYNC_TRELLO_DATA_ACTION'
export const SYNC_TRELLO_DATA_LOADING = 'SYNC_TRELLO_DATA_LOADING'

export const STORE_GITHUB_ISSUES_ACTION = 'STORE_GITHUB_ISSUES_ACTION'
export const STORE_GITHUB_ISSUES_LOADING = 'STORE_GITHUB_ISSUES_LOADING'


export const DESYNC_GITHUB_ACTION = 'DESYNC_GITHUB_ACTION'
export const DESYNC_GITHUB_LOADING = 'DESYNC_GITHUB_LOADING'

export const DESYNC_DISCORD_ACTION = 'DESYNC_DISCORD_ACTION'
export const DESYNC_DISCORD_LOADING = 'DESYNC_DISCORD_LOADING'

export const DESYNC_TRELLO_ACTION = 'DESYNC_TRELLO_ACTION'
export const DESYNC_TRELLO_LOADING = 'DESYNC_TRELLO_LOADING'
export const LOAD_RECURRING_PAYMENTS_ACTION = "LOAD_RECURRING_PAYMENTS_ACTION"
export const SET_RECURRING_PAYMENTS = "SET_RECURRING_PAYMENTS"
export const LOAD_RECURRING_PAYMENTS_LOADING = "LOAD_RECURRING_PAYMENTS_LOADING"

export const CREATE_RECURRING_PAYMENT_ACTION = "CREATE_RECURRING_PAYMENT_ACTION"
export const CREATE_RECURRING_PAYMENT_SUCCESS = "CREATE_RECURRING_PAYMENT_SUCCESS"
export const CREATE_RECURRING_PAYMENT_LOADING = "CREATE_RECURRING_PAYMENT_LOADING"

