export const SET_TOKEN_ACTION = 'SET_TOKEN_ACTION'
export const CREATE_ACCOUNT_ACTION = 'CREATE_ACCOUNT_ACTION'
export const CREATE_ACCOUNT_LOADING = 'CREATE_ACCOUNT_LOADING'
export const SET_USER_ACTION = 'SET_USER_ACTION'
export const SET_NETWORK_CONFIG = 'SET_NETWORK_CONFIG'
export const LOGOUT_ACTION = "LOGOUT_ACTION"

export const LOAD_DAOLIST_ACTION = "LOAD_DAOLIST_ACTION"
export const LOAD_DAOLIST_LOADING = "LOAD_DAOLIST_LOADING"
export const LOAD_DAOLIST_SUCCESS = "LOAD_DAOLIST_SUCCESS"

export const RESET_DAO_ACTION = "RESET_DAO_ACTION"
export const LOAD_DAO_ACTION = "LOAD_DAO_ACTION"
export const LOAD_DAO_LOADING = "LOAD_DAO_LOADING"
export const LOAD_DAO_SUCCESS = "LOAD_DAO_SUCCESS"
// project action types
export const CREATE_PROJECT_ACTION = 'CREATE_PROJECT_ACTION'
export const CREATE_PROJECT_LOADING = 'CREATE_PROJECT_LOADING'
export const SET_PROJECT_ACTION = 'SET_PROJECT_ACTION'
