export const SET_TOKEN_ACTION = 'SET_TOKEN_ACTION'
export const CREATE_ACCOUNT_ACTION = 'CREATE_ACCOUNT_ACTION'
export const CREATE_ACCOUNT_LOADING = 'CREATE_ACCOUNT_LOADING'
export const SET_USER_ACTION = 'SET_USER_ACTION'
export const SET_NETWORK_CONFIG = 'SET_NETWORK_CONFIG'
export const LOGOUT_ACTION = "LOGOUT_ACTION"

export const LOAD_DAOLIST_ACTION = "LOAD_DAOLIST_ACTION"
export const LOAD_DAOLIST_LOADING = "LOAD_DAOLIST_LOADING"
export const LOAD_DAOLIST_SUCCESS = "LOAD_DAOLIST_SUCCESS"

export const RESET_DAO_ACTION = "RESET_DAO_ACTION"
export const LOAD_DAO_ACTION = "LOAD_DAO_ACTION"
export const LOAD_DAO_LOADING = "LOAD_DAO_LOADING"
export const LOAD_DAO_SUCCESS = "LOAD_DAO_SUCCESS"

export const LOAD_TREASURY_ACTION = "LOAD_TREASURY_ACTION"
export const LOAD_TREASURY_LOADING = "LOAD_TREASURY_LOADING"
export const SET_TREASURY = "SET_TREASURY"
export const CREATE_TREASURY_TRANSACTION_ACTION = "CREATE_TREASURY_TRANSACTION_ACTION"
export const APPEND_TREASURY_TRANSACTION = "APPEND_TREASURY_TRANSACTION"
export const UPDATE_TREASURY_TRANSACTION_ACTION = "UPDATE_TREASURY_TRANSACTION_ACTION"
export const UPDATE_TREASURY_TRANSACTION = "UPDATE_TREASURY_TRANSACTION"
export const UPDATE_TX_LABEL_ACTION = "UPDATE_TX_LABEL_ACTION"
export const SET_TX_LABEL = "SET_TX_LABEL"